export enum ROUTES {
  // DOCUMENT APIS
  getAllPingEmails = 'getAllPingEmails',
  putPingSequenceSettings = 'putPingSequenceSettings',
  putPingSequenceDetails = 'putPingSequenceDetails',
  postPingSequenceSettings = 'postPingSequenceSettings',
  postPingSequenceDetails = 'postPingSequenceDetails',
  deletePingSequenceDetails = 'deletePingSequenceDetails',
  getPingSequenceDetails = 'getPingSequenceDetails',
  getPingSequenceSettings = 'getPingSequenceSettings',

  read = 'read',
  create = 'create',
  update = 'update',
  remove = 'remove',

  readById = 'readById',
  getPingSequenceDetailsById = 'getPingSequenceDetailsById',
  getPingSequenceById = 'getPingSequenceById',
  postPingEmail = 'postPingEmail',
  postPingEmailMg = 'postPingEmailMg',
  postStopPingEmail = 'postStopPingEmail',
  postStopPingEmailMg = 'postStopPingEmailMg',
  postTemporaryEmailBouncesWebhook = 'postTemporaryEmailBouncesWebhook',
  deletePingEmail = 'deletePingEmail',
  deletePingSequence = 'deletePingSequence',
  postSendPingPreviewEmail = 'postSendPingPreviewEmail',
  postPingEmailByDraftId = 'postPingEmailByDraftId',
  postPingsDetail = 'postPingsDetail',
  postMobilePingEmails = 'postMobilePingEmails',
  postMobileSearchPingEmailSummary = 'postMobileSearchPingEmailSummary',
  getSearchPingEmailSummary = 'getSearchPingEmailSummary',
  getRestartPingEmail = 'getRestartPingEmail',
  postCustomDomainPings = 'postCustomDomainPings',
  getCustomDomainPings = 'getCustomDomainPings',
  getPingSequenceListByOffset = 'getPingSequenceListByOffset',
}
