export enum ROUTES {
  getGoogleLogin = 'getGoogleLogin',
  getGoogleCallback = 'getGoogleCallback',
  getSession = 'getSession',
  register = 'register',
  login = 'login',
  getmobileGoogleLogin = 'getmobileGoogleLogin',
  getProfilePicByEmail = 'getProfilePicByEmail',
  putUpdateUser = 'putUpdateuser',
  getDeleteUser = 'getDeleteUser',
  postDeletingUser = 'postDeletingUser',
  getDeletingUserById = 'getDeletingUserById',
  getUser = 'getUser',
  postUserDevice = 'postUserDevice',
  postMobileUserDevice = 'postMobileUserDevice',
  postMobileUserData = 'postMobileUserData',
  getTwitterCallback = 'getTwitterCallback',
  getFacebookCallback = 'getFacebookCallback',
  postSetAdmin = 'postSetAdmin',
}
