export enum ROUTES {
  // DOCUMENT APIS
  getStatsInfo = 'getStatsInfo',
  getGraphData = 'getGraphData',
  getRecentUnreadEmailsCount = 'getRecentUnreadEmailsCount',
  getGraphUnreadEmailsCount = 'getGraphUnreadEmailsCount',
  getSignatureClicksCount = 'getSignatureClicksCount',
  postSelectPlan = 'postSelectPlan',

  getSignatureById = 'getSignatureById',
  getOptimization = 'getOptimization',
  getEmailCount = 'getEmailCount',
  getSignature = 'getSignature',
  getAllSignatures = 'getAllSignatures',
  getTeamManagement = 'getTeamManagement',
  getDashboardOld = 'getDashboardOld',
  getDashboard = 'getDashboard',
  getShowSpecificSentEmailById = 'getShowSpecificSentEmailById',
  getAccount = 'getAccount',
  getAllReadEmails = 'getAllReadEmails',
  getAllRecentUnreadEmails = 'getAllRecentUnreadEmails',
  getUnreadEmails = 'getUnreadEmails',
  getAllPreferences = 'getAllPreferences',
  getUpgrade = 'getUpgrade',
  getInvoice = 'getInvoice',
  getAllVideos = 'getAllVideos',
  getReferAFriend = 'getReferAFriend',
  getSupport = 'getSupport',
  getAllPingEmails = 'getAllPingEmails',
  getPingSequenceDetailsById = 'getPingSequenceDetailsById',
  getStopPingEmailById = 'getStopPingEmailById',
  getShowSpecificSentPingById = 'getShowSpecificSentPingById',
}
